apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-amd64-nodeaffinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-amd64-nodeaffinity
  template:
    metadata:
      labels:
        app: app-amd64-nodeaffinity
    spec:
      containers:
      - name: app-amd64-nodeaffinity
        image: registry/app-amd64:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key:  kubernetes.io/arch
                operator: In
                values:
                - amd64            
