apiVersion: fleet.azure.com/v1alpha1
kind: ClusterResourcePlacement
metadata:
  name: platformservices
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: platformservices