apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: platformservices
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: platformservices