kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zrs
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_ZRS 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zrsdisk
spec:
  selector:
    matchLabels:
      app: zrsdisk
  template:
    metadata:
      labels:
        app: zrsdisk
        demo: disks
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["/bin/bash"]
        args: ["-c", "while true; do date | tee -a /data/myfile.txt; sleep 15; done"]
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zrsdisk
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - "northeurope-1"   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zrsdisk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: zrs
  resources:
    requests:
      storage: 30Gi