# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myazurekeyvault
spec:
  provider: azure
  secretObjects:                             
  - data:
    - key: postgresqlurl                           
      objectName: postgresqlurl        
    secretName: psql-secret   
    type: Opaque 
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 8f084d68-7a09-47d5-85b9-e3403417cf95  # Here insert id from command: az aks show -g $prefix-rg -n $prefix-aks --query addonProfiles.azureKeyvaultSecretsProvider.identity.clientId -o tsv
    keyvaultName: tomaskubica8-kv                                 # Here insert you Key Vault name
    cloudName: ""        
    objects:  |
      array:
        - |
          objectName: postgresqlurl
          objectType: secret   
          objectVersion: ""         
    tenantId: d6af5f85-2a50-4370-b4b5-9b9a55bcb0dc   # Here insert your tenant id: az account show --query tenantId -o tsv