apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trusted-app
  template:
    metadata:
      labels:
        app: trusted-app
    spec:
      containers:
      - name: trusted-app
        image: ljishen/sysbench
        command: ["bash", "-c", "while true; do echo -e '\nKernel:'; uname -r; echo -e '\nCPU test:'; sysbench-1.0/sysbench/sysbench --test=cpu --threads=1 run | grep 'total time taken by event execution'; echo -e '\nRAM test:'; sysbench-1.0/sysbench/sysbench --test=memory run | grep 'total time taken by event execution'; done"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "4000m"
          requests:
            memory: "128Mi"
            cpu: "1000m"
