apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-app-burstable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trusted-app-burstable
  template:
    metadata:
      labels:
        app: trusted-app-burstable
    spec:
      containers:
      - name: sysbench
        image: ljishen/sysbench
        command: ["bash", "-c", "while true; do echo -e '\nKernel:'; uname -r; echo -e '\nCPU test:'; sysbench-1.0/sysbench/sysbench --test=cpu --num-threads=4 run | grep 'total time:'; echo -e '\nRAM test:'; sysbench-1.0/sysbench/sysbench --test=memory --num-threads=4 --memory-total-size=64M run | grep 'total time:'; done"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "4000m"
          requests:
            memory: "128Mi"
            cpu: "1000m"
