$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Tomas lendingclub demo pipeline

display_name: lendingclub-demo-pipeline
experiment_name: lendingclub-demo-experiment

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:demo

jobs:
  prepare_data:
    inputs:
      raw_data:
        type: uri_file
        path: azureml:lending_club_raw:1
        mode: download 
    type: command
    component: azureml:lending_club_process_data@latest
    outputs:
      processed_data:
  split_and_scale:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.prepare_data.outputs.processed_data}}
        mode: download 
      label_name: loan_repaid
    type: command
    component: azureml:split_and_scale@latest
    outputs:
      datasets:
  train:
    inputs:
      data:
        type: uri_file
        path: ${{parent.jobs.split_and_scale.outputs.datasets}}
        mode: download 
    type: command
    component: azureml:lending_club_train@latest
    outputs:
      model: