kind: Pod
apiVersion: v1
metadata:
  name: client-secrets
spec:
  serviceAccountName: kvaccess
  containers:
    - name: client
      image: nginx:latest
      volumeMounts:
      - name: mysecretmount
        mountPath: "/mnt/mysecretpath"
        readOnly: true
      env:
      - name: MY_SECRET
        valueFrom:
          secretKeyRef:
            name: mykubesecret
            key: mysecret
  volumes:
    - name: mysecretmount
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kv