apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageaccess
  namespace: default
  annotations:
    azure.workload.identity/client-id: {{ .Values.storage_access_client_id }}
  labels:
    azure.workload.identity/use: "true"