name: d-aks-arm64-create

on:
  workflow_dispatch:
  push:

env:
  TF_STATE_BLOB_ACCOUNT_NAME: tkubicastore
  TF_STATE_BLOB_CONTAINER_NAME: tfstate
  TF_STATE_BLOB_FILE: d-aks-arm64.tfstate
  TF_STATE_BLOB: d-aks-arm64.tfstate
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: demo
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./d-aks-arm64/terraform
        run: |
          terraform init \
            -backend-config="storage_account_name=$(TF_STATE_BLOB_ACCOUNT_NAME)" \
            -backend-config="container_name=$(TF_STATE_BLOB_CONTAINER_NAME)" \
            -backend-config="key=$(TF_STATE_BLOB)" 

      - name: Terraform apply
        working-directory: ./d-aks-arm64/terraform
        run: terraform apply -auto-approve

      - name: Get Terraform outputs
        run: echo ::set-output name=acr_name::$(terraform output -raw acr_name)
        id: tf-outputs

      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - name: ACR login
        working-directory: ./d-aks-arm64/terraform
        run: az acr login -n ${{ steps.tf-outputs.outputs.acr_name }}





      # - name: Build
      #   uses: docker/build-push-action@v2
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: ./d-aks-arm64/app
      #     file: ./Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: [$(terraform output -raw acr_name).azurecr.io/d-aks-arm64:latest]