name: d-aks-arm64-destroy

on:
  workflow_dispatch:

env:
  TF_STATE_BLOB_ACCOUNT_NAME: tkubicastore
  TF_STATE_RESOURCE_GROUP_NAME: base
  TF_STATE_BLOB_CONTAINER_NAME: tfstate
  TF_STATE_BLOB_FILE: d-aks-arm64.tfstate
  TF_STATE_BLOB: d-aks-arm64.tfstate
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: demo
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./d-aks-arm64/terraform
        run: |
          terraform init \
            -backend-config=storage_account_name=$TF_STATE_BLOB_ACCOUNT_NAME \
            -backend-config=resource_group_name=$TF_STATE_RESOURCE_GROUP_NAME \
            -backend-config=container_name=$TF_STATE_BLOB_CONTAINER_NAME \
            -backend-config=key=$TF_STATE_BLOB \
            -backend-config=client_id=$ARM_CLIENT_ID \
            -backend-config=subscription_id=$ARM_SUBSCRIPTION_ID \
            -backend-config=tenant_id=$ARM_TENANT_ID

      - name: Terraform destroy
        working-directory: ./d-aks-arm64/terraform
        run: terraform destroy -auto-approve